export type ContentIdeaFormat =
  | "Reel"
  | "TikTok"
  | "Photo"
  | "Carousel"
  | "Story Series"
  | "Campaign"
  | "Portfolio"
  | "UGC"
  | "Talking-head"
  | "Review"
  | "Educational";

export type ContentIdeaFramework = {
  id: string;
  format: ContentIdeaFormat;
  title: string;
  deliverable: string;
  description: string;
  hook: string;
  callToAction: string;
  shotList: string[];
  outreachUse: string;
  estimatedTime: string;
  stages?: string[];
  niches?: string[];
};

export const CONTENT_IDEA_FRAMEWORKS: ContentIdeaFramework[] = [
  {
    id: "hotel-proof-reel",
    format: "Reel",
    title: "60-Second Hotel Proof Reel",
    deliverable: "1 vertical reel (9:16), 25–45 sec, posted on {instagram} with location tag",
    description: "Arrival → room → detail → view. Text on screen, no voiceover required.",
    hook: "The kind of stay my audience books after watching this",
    callToAction: "Partnership inquiries — link in bio",
    shotList: [
      "Door opening or lobby arrival — 3 sec, text: Would you stay here?",
      "Bed, bathroom detail, window view — 15 sec total",
      "Coffee moment, pool, or balcony — 5 sec, text: Save for {travel}",
      "Export 9:16, luxury instrumental, post with property geotag",
    ],
    outreachUse: "Attach the link in your next boutique hotel pitch as proof you deliver property content.",
    estimatedTime: "60 min",
  },
  {
    id: "pov-arrival-reel",
    format: "Reel",
    title: "POV: First Impression Arrival",
    deliverable: "1 reel under 20 sec, local business tagged in {location}",
    description: "Works at a café, hotel lobby, or restaurant — no trip required.",
    hook: "POV: You just walked into the kind of place your audience saves",
    callToAction: "Save this for {location}",
    shotList: [
      "Walk in, pan to hero detail, hands on menu or door — 3 shots",
      "Text hook in first 2 seconds",
      "Geotag and tag the business if appropriate",
    ],
    outreachUse: "Tag the business, then pitch them next day with Restaurant or Boutique Hotel template.",
    estimatedTime: "45 min",
  },
  {
    id: "hotel-partnership-carousel",
    format: "Carousel",
    title: "5 Signs a Hotel Is Worth Partnering With",
    deliverable: "1 carousel, 7 slides, posted Tuesday or Thursday 10am {location} time",
    description: "Positions you as selective — brands want creators with standards.",
    hook: "After years of {niche} travel, I only recommend properties that pass these 5 tests",
    callToAction: "Which standard matters most? Comment 1–5",
    shotList: [
      "Slide 1: hook + your best hotel photo",
      "Slides 2–6: design, service, location, dining, value — one photo each",
      "Slide 7: I partner with {tier} properties — portfolio in bio",
      "Caption: 3 sentences on {positioning}",
    ],
    outreachUse: "Hotels see you as a curator — include this post link when pitching hosted stays.",
    estimatedTime: "75 min",
  },
  {
    id: "restaurant-night-reel",
    format: "Reel",
    title: "Restaurant Night: 4-Clip Structure",
    deliverable: "1 dining reel, 20–30 sec, restaurant tagged and geotagged in {location}",
    description: "Works without a partnership — pitch the restaurant the day after posting.",
    hook: "Date night in {location} — every course was worth it",
    callToAction: "Tag someone you'd bring here",
    shotList: [
      "Exterior/signage — 2 sec",
      "Ambiance wide + candlelight close-up — 5 sec each",
      "Two hero dishes plated — overhead and 45°",
      "Clink or dessert ending. Caption names the restaurant and one standout dish",
    ],
    outreachUse: "DM the restaurant next morning: Just posted a feature — open to a hosted tasting collaboration?",
    estimatedTime: "50 min",
  },
  {
    id: "pitch-day-stories",
    format: "Story Series",
    title: "3-Part Pitch Day Stories",
    deliverable: "3 story frames posted same day on {instagram}",
    description: "Shows brands you're actively pursuing partnerships.",
    hook: "What I actually do before I pitch a hotel",
    callToAction: "Reply PITCH if you want my outreach template",
    shotList: [
      "Frame 1: media kit or portfolio folder (blur personal info)",
      "Frame 2: Partnership Opportunities with one target circled — sending today",
      "Frame 3: poll — Should creators pitch hotels under 10K followers?",
    ],
    outreachUse: "Signals to hospitality brands you run a real outreach system — not waiting to be discovered.",
    estimatedTime: "25 min",
  },
  {
    id: "travel-mini-series",
    format: "Campaign",
    title: "3-Post Mini Series: {travel}",
    deliverable: "3 feed posts over 5 days + folder titled {travel} Case Study",
    description: "Complete trip arc you can screenshot for pitch decks.",
    hook: "I'm documenting {travel} the way hospitality brands wish creators would",
    callToAction: "Follow for Part 2 tomorrow",
    shotList: [
      "Monday: arrival reel — exterior + hook",
      "Wednesday: carousel — 5 experiences or amenities",
      "Friday: takeaway post — Would I return? verdict",
      "Screenshot all three for your media kit folder",
    ],
    outreachUse: "Paste the case study screenshots into your Hosted Stay Pitch as multi-touch proof.",
    estimatedTime: "3 hours",
  },
  {
    id: "grid-refresh",
    format: "Portfolio",
    title: "Grid Refresh for {dream} Partnerships",
    deliverable: "Updated 3×3 grid + 1 before/after carousel posted on {instagram}",
    description: "First thing a hotel GM checks when you pitch.",
    hook: "I rebuilt my grid to attract {dream} — here's what changed",
    callToAction: "A or B layout? Vote in comments",
    shotList: [
      "Screenshot current grid",
      "Archive 3 posts that don't signal {tier} quality",
      "Reorder: property shot, dining, {pillar} in top 6",
      "Post before/after carousel — caption states {goal}",
    ],
    outreachUse: "Your grid is your silent pitch — send a screenshot with every outreach DM this week.",
    estimatedTime: "2 hours",
    stages: ["emerging", "growing"],
  },
  {
    id: "media-kit-case-study",
    format: "Carousel",
    title: "Media Kit Case Study Post",
    deliverable: "1 carousel, 5 slides, with real engagement numbers from your best post",
    description: "Paste directly into pitches and your media kit PDF.",
    hook: "How one {niche} post drove real saves and DMs",
    callToAction: "Full media kit in bio",
    shotList: [
      "Slide 1: post screenshot + hook",
      "Slide 2: objective for the property or destination",
      "Slide 3: how you executed — format, timing, creative",
      "Slide 4: results — saves, reach, DMs (real numbers)",
      "Slide 5: available for similar collaborations",
    ],
    outreachUse: "Attach to every outreach email this week — closes {gap} in your portfolio.",
    estimatedTime: "80 min",
  },
  {
    id: "detail-photo-series",
    format: "Photo",
    title: "5-Photo Detail Series",
    deliverable: "1 gallery post, 5 vertical photos, consistent warm edit",
    description: "No people required — portfolio gold for design-forward hotel pitches.",
    hook: "Luxury is in the details — 5 frames from {location}",
    callToAction: "Which frame is your favorite? Comment 1–5",
    shotList: [
      "Linen or tile texture",
      "Window light or golden hour",
      "Tablescape or amenity detail",
      "Signature object — coffee, flowers, key",
      "Wide establishing shot",
    ],
    outreachUse: "Send with Boutique Hotel Pitch — design-led properties respond to this format.",
    estimatedTime: "45 min",
  },
  {
    id: "pack-with-me",
    format: "Reel",
    title: "Pack With Me: Creator Trip",
    deliverable: "1 reel, 20–30 sec, gear and outfits labeled on screen",
    description: "Shows brands you take creator trips seriously.",
    hook: "Everything in my bag for a paid creator trip to {travel}",
    callToAction: "Save for your next trip",
    shotList: [
      "Lay out camera, lenses, tripod, outfits, backup batteries",
      "8–10 quick cuts with text labels",
      "Caption ties to {equipment} and your {archetype} approach",
    ],
    outreachUse: "Send after a hotel replies to your first message — humanizes you before a call.",
    estimatedTime: "40 min",
  },
  {
    id: "brand-engagement-sprint",
    format: "Story Series",
    title: "Brand Visibility Engagement Sprint",
    deliverable: "20 comments on brand accounts + 3 screenshots saved to outreach tracker",
    description: "Gets you on brand radar before you pitch.",
    hook: "The commenting strategy that gets brand attention before you DM",
    callToAction: "Save this — do it before your next outreach wave",
    shotList: [
      "Pick 5 accounts from Partnership Opportunities",
      "4 thoughtful comments each — reference specific post details",
      "Screenshot 3 comments, log date in outreach tracker",
    ],
    outreachUse: "When you DM 3 days later, they may already recognize your name from comments.",
    estimatedTime: "30 min",
  },
  {
    id: "portfolio-week",
    format: "Campaign",
    title: "Portfolio Week: 4 Posts in 7 Days",
    deliverable: "4 feed posts + updated media kit with screenshots of each",
    description: "Run the week before your Day 15–21 outreach block.",
    hook: "Building partnership-ready proof this week — follow along",
    callToAction: "Day 1 of 4 — follow for the series",
    shotList: [
      "Day 1: detail photo series",
      "Day 2: educational carousel",
      "Day 3: reel",
      "Day 4: case study carousel",
      "End of week: add all four to media kit PDF",
    ],
    outreachUse: "Enter Week 3 outreach with 4 fresh proof posts — dramatically improves reply rates.",
    estimatedTime: "4 hours",
    stages: ["emerging", "growing"],
  },
  {
    id: "tiktok-hotel-tour",
    format: "TikTok",
    title: "15-Second Hotel Room Tour",
    deliverable: "1 TikTok, 12–18 sec, property tagged with trending audio",
    description: "Fast-cut room tour optimized for saves and shares — repurpose to Reels.",
    hook: "Would you book this room? Be honest.",
    callToAction: "Follow for more {tier} stays",
    shotList: [
      "Door open → bed → bathroom → view — 3 sec each",
      "Text overlay with room type and one standout detail",
      "Post with property tag; export same file for Instagram Reels",
    ],
    outreachUse: "TikTok proof shows multi-platform reach — mention both platforms in hotel pitches.",
    estimatedTime: "35 min",
  },
  {
    id: "tiktok-day-in-life",
    format: "TikTok",
    title: "Day in the Life: Creator on Property",
    deliverable: "1 TikTok, 30–45 sec, voiceover or text-on-screen",
    description: "Behind-the-scenes creator workflow at a hotel or villa — brands love seeing your process.",
    hook: "What I actually film when a hotel invites me to stay",
    callToAction: "Save this workflow for your next trip",
    shotList: [
      "Morning: coffee + planning shot list on phone",
      "Midday: 3 B-roll clips of property details",
      "Evening: editing on laptop in room — blur screen if needed",
      "End card: follow for {niche} hospitality content",
    ],
    outreachUse: "Send to properties considering hosted stays — proves you deliver more than one post.",
    estimatedTime: "90 min",
  },
  {
    id: "ugc-hook-reels",
    format: "UGC",
    title: "3 Hook-Led UGC Reels for Brands",
    deliverable: "3 vertical clips (9:16), 15–20 sec each, no watermark, brand-ready",
    description: "Platform-ready assets for a property's paid social — not a public post on your feed.",
    hook: "Three hooks a hotel can run as ads tomorrow",
    callToAction: "N/A — deliver via Drive folder to brand contact",
    shotList: [
      "Reel 1: arrival hook — Would you stay here?",
      "Reel 2: amenity hook — The detail that sold me",
      "Reel 3: CTA hook — Book direct for the best rate",
      "Export clean files with naming: BrandName_Hook1_9x16",
    ],
    outreachUse: "Lead with Paid UGC Pitch — attach one sample clip as proof of ad-ready quality.",
    estimatedTime: "2 hours",
    stages: ["growing", "established"],
  },
  {
    id: "ugc-photo-pack",
    format: "UGC",
    title: "15-Photo UGC Pack",
    deliverable: "15 edited photos, consistent tone, delivered in a labeled folder",
    description: "Website and social-ready images without requiring a public collaboration post.",
    hook: "N/A — visual pack for brand channels",
    callToAction: "N/A — deliver via shared folder",
    shotList: [
      "5 detail shots: linen, tile, amenities, tablescape, light",
      "5 experience shots: pool, dining, lobby, exterior, view",
      "5 lifestyle-adjacent shots: coffee, keys, robe, balcony, walkway",
      "Edit in one cohesive preset; export full-res JPEGs",
    ],
    outreachUse: "Offer in Paid UGC Pitch as a lower-commitment entry before a full stay collaboration.",
    estimatedTime: "2.5 hours",
    stages: ["growing", "established"],
  },
  {
    id: "talking-head-positioning",
    format: "Talking-head",
    title: "60-Second Positioning Video",
    deliverable: "1 talking-head reel, 45–60 sec, posted on {instagram}",
    description: "Introduce who you create for and what hospitality brands get from working with you.",
    hook: "I help {tier} hospitality brands reach travelers who actually book",
    callToAction: "Partnership inquiries — link in bio",
    shotList: [
      "Hook in first 3 seconds — state your niche and audience",
      "3 bullets: what you deliver, who you reach, proof you have",
      "Close with availability for hosted stays and UGC",
      "Caption expands {positioning} in 2 sentences",
    ],
    outreachUse: "Pin to profile and link in every pitch — replaces a long intro paragraph.",
    estimatedTime: "45 min",
  },
  {
    id: "talking-head-pitch-tips",
    format: "Talking-head",
    title: "3 Outreach Tips for Hospitality Creators",
    deliverable: "1 educational reel, 30–45 sec, saves-focused",
    description: "Share practical outreach advice — positions you as a serious operator.",
    hook: "3 things I do before I pitch a boutique hotel",
    callToAction: "Save this before your next outreach wave",
    shotList: [
      "Tip 1: comment on brand posts 3 days before DMing",
      "Tip 2: attach one proof post link in every pitch",
      "Tip 3: follow up once — confidently, not desperately",
      "End with your {instagram} handle for partnership inquiries",
    ],
    outreachUse: "Hospitality marketers who discover this video may DM you first.",
    estimatedTime: "40 min",
  },
  {
    id: "hospitality-review-carousel",
    format: "Review",
    title: "Honest Stay Review Carousel",
    deliverable: "1 carousel, 6 slides — verdict, highlights, and one improvement",
    description: "Balanced review format brands trust — not pure promotion.",
    hook: "I stayed here so you don't have to guess — my honest verdict",
    callToAction: "Would you book? Yes or no in comments",
    shotList: [
      "Slide 1: property hero + hook",
      "Slides 2–4: best moments — room, dining, service",
      "Slide 5: one honest improvement (keeps credibility)",
      "Slide 6: overall score + who this stay is perfect for",
    ],
    outreachUse: "Shows hotels you review with integrity — attach when pitching similar-tier properties.",
    estimatedTime: "70 min",
  },
  {
    id: "restaurant-review-reel",
    format: "Review",
    title: "60-Second Restaurant Verdict Reel",
    deliverable: "1 reel with on-screen rating and 3 standout moments",
    description: "Quick verdict format — high save rate for dining discovery content.",
    hook: "Worth the reservation? My honest take after one visit",
    callToAction: "Save for your next date night in {location}",
    shotList: [
      "Opening: exterior + text rating placeholder",
      "3 clips: ambiance, signature dish, service moment",
      "Closing verdict on screen — Worth it / Skip / Special occasion only",
      "Tag restaurant; pitch collaboration the next day if positive",
    ],
    outreachUse: "Restaurants see balanced praise as credible — easier path to hosted tasting offers.",
    estimatedTime: "55 min",
  },
  {
    id: "educational-rates-carousel",
    format: "Educational",
    title: "What to Charge: Creator Rates Explainer",
    deliverable: "1 carousel, 5 slides, educational tone",
    description: "Positions you as a professional — brands respect creators who understand value.",
    hook: "What {stage} hospitality creators should charge — and why",
    callToAction: "Save for your next negotiation",
    shotList: [
      "Slide 1: hook + your tier ({tier})",
      "Slide 2: hosted stay vs. paid UGC vs. campaign",
      "Slide 3: what factors raise your rate — proof, usage rights, deliverables",
      "Slide 4: sample range for {followers} creators (use Resources rate card)",
      "Slide 5: how to present rates in a pitch without underselling",
    ],
    outreachUse: "Share with brands who ask about rates — shows confidence in paid partnerships.",
    estimatedTime: "60 min",
    stages: ["growing", "established"],
  },
  {
    id: "educational-shot-list",
    format: "Educational",
    title: "Hotel Content Shot List Carousel",
    deliverable: "1 carousel teaching your filming system — 8 slides",
    description: "Educational content that doubles as proof of your hospitality expertise.",
    hook: "The 8 shots I capture at every hotel to get partnership replies",
    callToAction: "Which shot do you always forget? Comment below",
    shotList: [
      "Slide 1: hook",
      "Slides 2–8: one shot type each with example frame",
      "Caption: tie to {pillar} and {equipment}",
      "Save to Highlights: Creator Tips",
    ],
    outreachUse: "Properties see you as a professional content partner, not a casual guest with a phone.",
    estimatedTime: "75 min",
  },
  {
    id: "story-amenity-sequence",
    format: "Story Series",
    title: "5-Frame Amenity Story Sequence",
    deliverable: "5 connected story frames with poll and link sticker",
    description: "Interactive story arc — strong engagement signal for brands reviewing your profile.",
    hook: "5 details that make this stay feel {tier}",
    callToAction: "Poll: Which amenity matters most to you?",
    shotList: [
      "Frame 1: arrival text hook",
      "Frames 2–4: one amenity each — spa, dining, room detail",
      "Frame 5: poll + link sticker to portfolio or media kit",
    ],
    outreachUse: "Screenshot story insights (replies, poll votes) for your media kit metrics slide.",
    estimatedTime: "30 min",
  },
  {
    id: "villa-cinematic-reel",
    format: "Reel",
    title: "Cinematic Villa Tour Reel",
    deliverable: "1 reel, 40–60 sec, slow transitions and luxury audio",
    description: "For villa and retreat pitches — shows you can deliver aspirational property storytelling.",
    hook: "The villa my audience saves for their next {travel} escape",
    callToAction: "Partnership inquiries for villa and retreat properties",
    shotList: [
      "Drone or wide establishing shot if available — otherwise exterior walk-up",
      "Pool, living space, primary suite, outdoor dining — 8 sec each",
      "Golden hour detail montage — 10 sec",
      "End card with property name and your handle",
    ],
    outreachUse: "Lead with Luxury Villa Pitch — attach this reel or a similar property tour as proof.",
    estimatedTime: "2 hours",
    stages: ["growing", "established"],
  },
];
